#!/bin/bash
git for-each-ref --format="%(refname:short) %(upstream:short)" refs/heads | \
while read local remote
do
    [ -z "$remote" ] && continue
    git rev-list --left-right ${local}...${remote} -- 2>/dev/null >/tmp/git_upstream_status_delta || continue
    LEFT_AHEAD=$(grep -c '^<' /tmp/git_upstream_status_delta)
    RIGHT_AHEAD=$(grep -c '^>' /tmp/git_upstream_status_delta)
    if [ "$LEFT_AHEAD" != "0" ] 
        then 
        LEFT_AHEAD="\e[31m$LEFT_AHEAD\e[39m"
        local="\e[1m$local\e[0m"
    fi

    echo -e "$local (ahead $LEFT_AHEAD) | (behind $RIGHT_AHEAD) $remote"
done
